FROM ubuntu:16.04

RUN mkdir -p /opt/klot-io

WORKDIR /opt/klot-io

RUN wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh && \
    chmod +x pishrink.sh && \
    mv pishrink.sh /usr/local/bin
    
CMD "sh"
