FROM python:3.6-alpine3.10

RUN mkdir -p /opt/klot-io

WORKDIR /opt/klot-io

RUN apk add git build-base openssl-dev libffi-dev linux-headers

ADD config_requirements.txt requirements.txt

RUN pip install -r requirements.txt

ADD lib lib
ADD bin bin

ENV PYTHONPATH "/opt/klot-io/lib:${PYTHONPATH}"

CMD "sh"
