FROM python:3.6-alpine3.8

RUN mkdir -p /opt/clot-io

WORKDIR /opt/clot-io

RUN apk add build-base openssl-dev libffi-dev

ADD requirements.txt .

RUN pip install -r requirements.txt

ADD lib lib
ADD bin bin

ENV PYTHONPATH "/opt/clot-io/lib:${PYTHONPATH}"

CMD "sh"
