FROM python:2.7-alpine3.9

RUN mkdir -p /opt/klot-io

WORKDIR /opt/klot-io

RUN apk add build-base openssl-dev libffi-dev git

ADD config_requirements.txt requirements.txt

RUN pip install -r requirements.txt

ADD lib lib
ADD bin bin

ENV PYTHONPATH "/opt/klot-io/lib:${PYTHONPATH}"

CMD "/opt/klot-io/bin/api.py"